### ISSUE TITLE
ReferenceError: callback is not defined

### ISSUE THREAD

**Issue by boggdan95** [SeverinDK/moment-timer#16]
I'm using moment-timer for a server based in node js. 

This is how I'm calling the packeges.

`var moment = require('moment');
moment().format();
var moment = require('moment-timer');`

When I try to run the timer, this error appears. 

`let timer = new moment.duration(1000).timer(callback);
  ReferenceError: callback is not defined`

**Comment by SeverinDK** [comment]
Need to see some more code.

**Comment by SeverinDK** [comment]
Closing this issue. I assume that you haven't defined the callback anywhere. The code example you provide will never work.
