### ISSUE TITLE
Can't stop timer

### ISSUE THREAD

**Issue by frutality** [SeverinDK/moment-timer#2]
Hi!

Trying to stop timer once it runs out.

```
var realTimer;
  realTimer = moment.duration(5, 'seconds').timer({
    loop: false,
    start: true
  }, function () {
    console.log('timer cb');
    realTimer.stop();
    console.log(realTimer.isStopped()); // false
  });
```

Even tried to stop it like this:
```
setTimeout(function () {
    realTimer.stop();
    console.log(realTimer.isStopped()); // false
  }, 10000);
```

**Comment by SeverinDK** [comment]
I will look into it as soon as possible. Apparently there is a problem with the way the non-loop timer works. After its duration reaches zero, it sets a variable that prevents it from calling .stop()

**Comment by SeverinDK** [comment]
Sorry that I haven't been able to get around to this problem yet. I will look at it tomorrow or the day after that. I have been busy with some new job stuff, that had first priority. But I will get to it asap :)

**Comment by frutality** [comment]
Ah, don't worry. I decided to use standard js setTimeout for my goals. Probably in more complicated cases moment-timer would be very helpful, but my case is simple :)

**Comment by SeverinDK** [comment]
No problem. I will still come up with a fix for it, just in case someone else runs into the same problem.

**Comment by yigitaybuga** [comment]
Any news on this? It is almost a year.
