### ISSUE TITLE
Seems to repeatedly call callback if it returns false

### ISSUE THREAD

**Issue by barrychapman** [SeverinDK/moment-timer#21]
I have the following implemented:

                TICKTOCK[mkr.ASSET_TAG] = moment.duration(CONFIG.setting('APP.UPDATE_FREQUENCY_X_SECS'), 'seconds').timer(
                    {
                        loop: true
                    },
                    function() {
                        updateMarkers();
                    }
                );

       let updateMarkers = function() {
            if (!Scope.isUpdating) {
                Scope.isUpdating = true;
                console.log('Updating map');
                $def = $.Deferred;

                $.ajax(
                    {
                        url: CONFIG.setting('ENDPOINTS.UPDATE_MAP'),
                        data: {},
                        dataType: 'json',
                        type: 'GET',
                        success: function(response) {
                            if (response.status) {
                                var data = response.data;

                                for (device in data) {
                                    var assetTag = data[device].device.asset_tag;
                                    var coords   = data[device].locations.shift();
                                    var lat      = coords.normalized_lat;
                                    var lng      = coords.normalized_lng;
                                    setMarker(assetTag, lat, lng);
                                }

                            }
                        },
                        complete: function(xhr, status) {
                            Scope.isUpdating = false;
                        },
                        error: function(xhr, status, error) {
                            alert('An error occurred while updating the map');
                        }
                    }
                );
                return true;
            }
            return false;
        };

However, if that callback at the bottom returns false, the function seems to get called infinitely. Is this expected behavior?

Thanks!

**Comment by SeverinDK** [comment]
Thank you for reporting the issue.

Just need to be sure we're on the same page. How do you mean it gets called infinitely? I see you have the loop param set, which would make it loop again and again?

**Comment by SeverinDK** [comment]
I assume you found a solution. Closing the issue.
