### ISSUE TITLE
executeAfterWait requires a wait period

### ISSUE THREAD

**Issue by VariableVixen** [SeverinDK/moment-timer#23]
I know that it's probably WAI, but I end up with a lot of situations where I need to execute a function now, and then every _x_ seconds after. The only way right now to do this in moment-timer is to set a `wait` period of one millisecond, because [the constructor checks for the wait period being greater than zero](https://github.com/SeverinDK/moment-timer/blob/0ad5f84870cacb0cbfa3821f01885c6dedac1221/lib/moment-timer.js#L25) when handling `executeAfterWait`.

Suggestion: replace
```javascript
if (attributes.wait > 0) {
	var self = this;
	setTimeout(function () {
		if (attributes.executeAfterWait) {
			callback();
		}
		self.start();
	}, attributes.wait);
} else {
	this.start();
}
```
with
```javascript
if (attributes.executeAfterWait) {
	if (attributes.wait > 0) {
		var self = this;
		setTimeout(function () {
			callback();
			self.start();
		}, attributes.wait);
	} else {
		callback();
		this.start();
	}
} else {
	this.start();
}
```
or similar. Alternatively, timeouts can be set with a period of `0` which executes immediately, allowing that specific check to become `(attributes.wait || 0) >= 0` instead, to allow for null to act as zero in event that no wait period was listed.

**Comment by SeverinDK** [comment]
Seems like a fair request. Feel free to do a PR or I will look more into it myself, one of the next days. Thank you for the feedback.

**Comment by VariableVixen** [comment]
Can do. Although, as I finished making the edit to my fork, I had an idea - should I add a new attribute, like `executeImmediately` maybe, that does this and then leave the `executeAfterWait` parts alone?

Effective changes:

| `loop`   | `duration` | `wait` | `executeAfterWait` | `executeImmediately` | Effect |
|----------|------------|--------|--------------------|----------------------|--------|
| _either_ | _any_      | _any_  | _either_           | `false`              | Current implementation |
| `true`  | `1000`     | `5000` | `true`              | `true`               | Execute callback, wait five seconds, execute callback, continue executing callback every second |
| `true`  | `1000`     | `5000` | `false`             | `true`               | Execute, wait five seconds, start interval to execute every second |
| `true`  | `1000`     | `0`    | _either_            | `true`               | Execute callback, continue executing callback every second (same effect as my original proposal) |
| `false` | `1000`     | `5000` | `true`              | `true`               | Execute, wait five seconds, execute, wait one second, execute, stop |
| `false` | `1000`     | `5000` | `false`             | `true`               | Execute, wait six seconds, execute (technically _wait five, start one second timer to execute_, not sure why this one would ever be used - suppose you could just add `duration` and `wait` and set one timer instead) |
| `false` | `1000`     | `0`    | _either_            | `true`               | Execute callback, wait one second, execute callback (same effect as my original proposal) |

They'd be equally easy to implement, and on my own project I'd use this one for versatility, but I don't know if you'd want the extra attribute cluttering things.

**Comment by VariableVixen** [comment]
Nevermind, I just opened a PR for each. Take whichever you like, although the second would keep backwards compatibility better for edge cases where the current behaviour is expected/needed.
